INSERT OR REPLACE INTO LocalizedText
(Tag, Text, Language) VALUES

( 'LOC_LMPT4U_HERDSMANCIVITASRESOURCES_CONFIG_NAME',
  '[ICON_ProductionQueue] Herdsman herds Penguins',
  'en_US' ),
( 'LOC_LMPT4U_HERDSMANCIVITASRESOURCES_CONFIG_DESC',
  '[COLOR:SuzerainDark]Mod: Herdsman[ENDCOLOR] (by AOM)[NEWLINE][ICON_ProductionQueue] Compatibility patch by H.Humpel.[NEWLINE][NEWLINE]This patch lets the herdsman use the resource Penguins from the "CIVITAS Resources" mod.',
  'en_US' ),
( 'LOC_LMPT4U_HERDSMANFURS_CONFIG_NAME',
  '[ICON_ProductionQueue] Herdsman herds Foxes',
  'en_US' ),
( 'LOC_LMPT4U_HERDSMANFURS_CONFIG_DESC',
  '[COLOR:SuzerainDark]Mod: Herdsman[ENDCOLOR] (by AOM)[NEWLINE][ICON_TechBoosted] Improvement patch by H.Humpel.[NEWLINE][NEWLINE]This patch lets the herdsman use the resource Furs.',
  'en_US' ),
( 'LOC_LMPT4U_HERDSMANGUILDMASTER_CONFIG_NAME',
  '[ICON_TechBoosted] Herdsman Guildmaster patch',
  'en_US' ),
( 'LOC_LMPT4U_HERDSMANGUILDMASTER_CONFIG_DESC',
  '[COLOR:SuzerainDark]Mod: Herdsman[ENDCOLOR] (by AOM)[NEWLINE][ICON_TechBoosted] Improvement patch by H.Humpel.[NEWLINE][NEWLINE]This patch adds the herdsman to Governor Liang''s "Guildmaster" promotion.',
  'en_US' ),
( 'LOC_LMPT4U_HERDSMANINLATINAMERICA_CONFIG_NAME',
  '[ICON_ProductionQueue] Herdsman in Latin America patch',
  'en_US' ),
( 'LOC_LMPT4U_HERDSMANINLATINAMERICA_CONFIG_DESC',
  '[COLOR:SuzerainDark]Mod: Herdsman[ENDCOLOR] (by AOM)[NEWLINE][ICON_ProductionQueue] Compatibility patch by H.Humpel.[NEWLINE][NEWLINE]This patch lets the herdsman use the resources from the "Latin American Resources" mod.',
  'en_US' ),
( 'LOC_LMPT4U_HERDSMANRESOURCEFUL2_CONFIG_NAME',
  '[ICON_ProductionQueue] Herdsman herds Ham',
  'en_US' ),
( 'LOC_LMPT4U_HERDSMANRESOURCEFUL2_CONFIG_DESC',
  '[COLOR:SuzerainDark]Mod: Herdsman[ENDCOLOR] (by AOM)[NEWLINE][ICON_ProductionQueue] Compatibility patch by H.Humpel.[NEWLINE][NEWLINE]This patch lets the herdsman use the resource Ham from the "Resourceful 2" mod.',
  'en_US' ),
( 'LOC_LMPT4U_HERDSMANSUKRITACTSRESOURCES_CONFIG_NAME',
  '[ICON_ProductionQueue] Herdsman herds Bisons',
  'en_US' ),
( 'LOC_LMPT4U_HERDSMANSUKRITACTSRESOURCES_CONFIG_DESC',
  '[COLOR:SuzerainDark]Mod: Herdsman[ENDCOLOR] (by AOM)[NEWLINE][ICON_ProductionQueue] Compatibility patch by H.Humpel.[NEWLINE][NEWLINE]This patch lets the herdsman use the resource Bisons from the "Sukritact''s Resources" mod.',
  'en_US' ),

( 'LOC_LMPT4U_HERDSMANCIVITASRESOURCES_CONFIG_NAME',
  '[ICON_ProductionQueue] Hirte hütet Pinguine',
  'de_DE' ),
( 'LOC_LMPT4U_HERDSMANCIVITASRESOURCES_CONFIG_DESC',
  '[COLOR:SuzerainDark]Mod: Herdsman[ENDCOLOR] (by AOM)[NEWLINE][ICON_ProductionQueue] Kompatibilitäts-Patch von H.Humpel.[NEWLINE][NEWLINE]Dieser Patch läßt den Hirten die Ressource Pinguine aus dem Mod "CIVITAS Resources" nutzen.',
  'de_DE' ),
( 'LOC_LMPT4U_HERDSMANFURS_CONFIG_NAME',
  '[ICON_ProductionQueue] Herdsman hütet Füchse',
  'de_DE' ),
( 'LOC_LMPT4U_HERDSMANFURS_CONFIG_DESC',
  '[COLOR:SuzerainDark]Mod: Herdsman[ENDCOLOR] (by AOM)[NEWLINE][ICON_TechBoosted] Verbesserungs-Patch von H.Humpel.[NEWLINE][NEWLINE]Dieser Patch läßt den Hirten die Ressource Pelze nutzen.',
  'de_DE' ),
( 'LOC_LMPT4U_HERDSMANGUILDMASTER_CONFIG_NAME',
  '[ICON_TechBoosted] Hirte Gildenmeister Patch',
  'de_DE' ),
( 'LOC_LMPT4U_HERDSMANGUILDMASTER_CONFIG_DESC',
  '[COLOR:SuzerainDark]Mod: Botanist[ENDCOLOR] (by AOM)[NEWLINE][ICON_TechBoosted] Verbesserungs-Patch von H.Humpel.[NEWLINE][NEWLINE]Dieser Patch fügt den Hirten zu Gouverneur Liangs "Gildenmeister"-Beförderung hinzu.',
  'de_DE' ),
( 'LOC_LMPT4U_HERDSMANINLATINAMERICA_CONFIG_NAME',
  '[ICON_ProductionQueue] Hirte in Lateinamerika Patch',
  'de_DE' ),
( 'LOC_LMPT4U_HERDSMANINLATINAMERICA_CONFIG_DESC',
  '[COLOR:SuzerainDark]Mod: Herdsman[ENDCOLOR] (by AOM)[NEWLINE][ICON_ProductionQueue] Kompatibilitäts-Patch von H.Humpel.[NEWLINE][NEWLINE]Dieser Patch läßt den Hirten die Ressourcen aus dem Mod "Latin American Resources" nutzen.',
  'de_DE' ),
( 'LOC_LMPT4U_HERDSMANRESOURCEFUL2_CONFIG_NAME',
  '[ICON_ProductionQueue] Hirte hütet Schinken',
  'de_DE' ),
( 'LOC_LMPT4U_HERDSMANRESOURCEFUL2_CONFIG_DESC',
  '[COLOR:SuzerainDark]Mod: Herdsman[ENDCOLOR] (by AOM)[NEWLINE][ICON_ProductionQueue] Kompatibilitäts-Patch von H.Humpel.[NEWLINE][NEWLINE]Dieser Patch läßt den Hirten die Ressource Schinken aus dem Mod "Resourceful 2" nutzen.',
  'de_DE' ),
( 'LOC_LMPT4U_HERDSMANSUKRITACTSRESOURCES_CONFIG_NAME',
  '[ICON_ProductionQueue] Hirte hütet Bisons',
  'de_DE' ),
( 'LOC_LMPT4U_HERDSMANSUKRITACTSRESOURCES_CONFIG_DESC',
  '[COLOR:SuzerainDark]Mod: Herdsman[ENDCOLOR] (by AOM)[NEWLINE][ICON_ProductionQueue] Kompatibilitäts-Patch von H.Humpel.[NEWLINE][NEWLINE]Dieser Patch läßt den Hirten die Ressource Bisons aus dem Mod "Sukritact''s Resources" nutzen.',
  'de_DE' );
