INSERT OR REPLACE INTO LocalizedText
(Tag, Text, Language) VALUES

( 'LOC_LMPT4U_HEADER_CONFIG_NAME',
  '[ICON_New] [COLOR_LIGHTBLUE]LET ME PATCH THAT FOR YOU[ENDCOLOR] [ICON_New]',
  'en_US' ),
( 'LOC_LMPT4U_HEADER_CONFIG_DESC',
  '',
  'en_US' ),
( 'LOC_LMPT4U_HEADER_CONFIG_NAME',
  '[ICON_New] [COLOR_LIGHTBLUE]LET ME PATCH THAT FOR YOU[ENDCOLOR] [ICON_New]',
  'de_DE' ),
( 'LOC_LMPT4U_HEADER_CONFIG_DESC',
  '',
  'de_DE' );
