INSERT INTO Improvement_ValidFeatures(ImprovementType, FeatureType)
VALUES ('IMPROVEMENT_TRANSPLANT_RICE','FEATURE_FLOODPLAINS_TUNDRA');

INSERT INTO Resource_ValidFeatures(ResourceType, FeatureType)
VALUES ('RESOURCE_RICE','FEATURE_FLOODPLAINS_TUNDRA');
